# Amina S driver
# Copyright (c) 2025 Kristian Kleiveland
# Licensed under the MIT License.

name: "Amina S EV Charger"
packageKey: "amina-s-driver"
permissions:
  zigbee: {}
profiles:
  - amina-profile
